# Setup
title:        The Ethics of Algorithms
tagline:      An exploration of automation, black boxes, and their impacts
baseurl:      "clusteredcrimemaps/"
paginate:     1

# About/contact
author:
  name:       Marquette Computational Social Science Lab
  url:        https://github.com/marquettecomputationalsocialscience

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
